Repository PI-coffeeBreak/frontend, pull requests merged in 2025-04, with the labels that each got.

#19 Scrum 123 connect frontend with backend
  package-lock.json
  package.json
  public/template.xlsx
  src/components/Activity.jsx
  src/components/Navbar.jsx
  src/components/Pagination.jsx
  src/components/PluginSettingsModal.jsx
  src/components/Sidebar.jsx
  src/components/ThemeCustomizer.jsx
  src/consts.js
  src/pages/Activities.jsx
  src/pages/Plugins.jsx
  src/pages/PluginsSettingEx.json
  src/pages/Schedule.jsx
  src/pages/Users.jsx
  src/styles.css
  vite.config.js
Labels: enhancement

#18 Scrum 122 register event initial config
  src/App.jsx
  src/pages/EventSetup.jsx
  src/pages/Register.jsx
  src/styles.css
Labels: enhancement

#21 Scrum 141 refactor create axios context organizer app
  src/App.jsx
  src/components/ThemeCustomizer.jsx
  src/consts.js
  src/contexts/ActivitiesContext.jsx
  src/contexts/PluginsContext.jsx
  src/contexts/ThemeContext.jsx
  src/contexts/UsersContext.jsx
  src/pages/Activities.jsx
  src/pages/Plugins.jsx
  src/pages/Schedule.jsx
  src/pages/Users.jsx
Labels: enhancement

#27 Scrum 158 frontend homepage customization page
  .talismanrc
  package-lock.json
  package.json
  src/App.jsx
  src/components/CommonInputs.jsx
  src/components/ComponentConfigurations.jsx
  src/components/PluginSettingsModal.jsx
  src/components/SortableItem.jsx
  src/components/componentsMap.jsx
  src/contexts/ActivitiesContext.jsx
  src/contexts/ComponentsContext.jsx
  src/contexts/PagesContext.jsx
  src/contexts/PluginsContext.jsx
  src/contexts/ThemeContext.jsx
  src/contexts/UsersContext.jsx
  src/pages/HomeEditor.jsx
  src/pages/Schedule.jsx
Labels: enhancement

#28 Scrum 158 frontend homepage customization page
  src/App.jsx
  src/components/Components.jsx
  src/components/Sidebar.jsx
  src/components/SortableItem.jsx
  src/contexts/ComponentsContext.jsx
  src/contexts/NotificationContext.jsx
  src/contexts/PagesContext.jsx
  src/pages/BaseConfiguration.jsx
  src/pages/HomeEditor.jsx
  src/pages/PageEditor.jsx
  src/pages/PageEditorWrapper.jsx
  src/pages/PagesList.jsx
Labels: enhancement

#30 Scrum 144 implement auth in frontend
  package-lock.json
  package.json
  src/App.jsx
  src/PrivateRoute.js
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
  src/consts.js
  src/keycloak.js
  src/main.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
  vite.config.js
Labels: enhancement

#32 Menu editor page
  .talismanrc
  package-lock.json
  package.json
  src/App.jsx
  src/components/IconSelector.jsx
  src/components/Sidebar.jsx
  src/contexts/MenuContext.jsx
  src/pages/MenuEditor.jsx
Labels: enhancement

#40 Scrum 197 improve activity management
  src/components/Activity.jsx
  src/components/activities/ActivityFilters.jsx
  src/components/activities/ActivityList.jsx
  src/components/activities/CreateActivityCards.jsx
  src/components/activities/ExcelImportModal.jsx
  src/components/activities/NewSessionModal.jsx
  src/components/common/Modal.jsx
  src/contexts/ActivitiesContext.jsx
  src/hooks/useForm.js
  src/pages/Activities.jsx
  src/pages/Schedule.jsx
Labels: bug, enhancement

#42 Fix/eventimageandlinks
  src/App.jsx
  src/components/Sidebar.jsx
  src/pages/AuthRedirect.jsx
  src/pages/Home.jsx
Labels: bug

#48 Scrum 202 edit event info
  public/brown_bean.svg
  public/joao.jpg
  public/white_bean.svg
  src/App.jsx
  src/components/Sidebar.jsx
  src/contexts/EventContext.jsx
  src/contexts/MediaContext.jsx
  src/pages/EventEditor.jsx
  src/pages/EventSetup.jsx
  src/pages/Home.jsx
  src/utils/LocationUtils.jsx
Labels: enhancement

#51 Scrum 216 fix dnd problems in page editor page
  src/components/event_maker/pages/DynamicComponentConfiguration.jsx
  src/components/event_maker/pages/PageContent.jsx
  src/components/event_maker/pages/SortableItemLayout.jsx
  src/pages/page_editor/CreatePage.jsx
  src/pages/page_editor/EditPage.jsx
Labels: bug, enhancement

#49 Scrum 177 component with event location link
  package-lock.json
  package.json
  src/components/event_maker/pages/components/Location.jsx
  src/components/event_maker/pages/components/index.js
Labels: enhancement

#56 fix functions passed to dynamicconfiguration
  src/components/event_maker/pages/PageContent.jsx
Labels: bug

#57 change update and create page handlers
  src/pages/page_editor/CreatePage.jsx
  src/pages/page_editor/EditPage.jsx
  src/utils/pageUtils.js
Labels: bug

#61 modified get pages link
  src/contexts/PagesContext.jsx
Labels: enhancement

#50 sponsor component preview and context
  .talismanrc
  src/components/event_maker/pages/components/Sponsors.jsx
  src/components/event_maker/pages/components/index.js
  src/contexts/Provider.jsx
  src/contexts/SponsorsContext.jsx
Labels: enhancement

#52 Scrum 230 fix sidebar frontend
  src/App.jsx
  src/components/DashboardCard.jsx
  src/components/DropdownMenu.jsx
  src/components/Sidebar.jsx
  src/pages/EventMaker.jsx
  src/pages/Instantiate.jsx
  src/pages/Management.jsx
Labels: enhancement

#60 avoid multiple context calls
  src/pages/Home.jsx
Labels: bug

#66 Scrum 218 fix time zones on scheduler
  .talismanrc
  src/pages/Schedule.jsx
Labels: enhancement
