Repository PI-coffeeBreak/frontend, pull requests merged in 2025-05, with the labels that each got.

#69 Floor Plan Management Page
  src/App.jsx
  src/pages/FloorPlans.jsx
Labels: enhancement

#71 Fix/remove plugin contexts
  src/contexts/Provider.jsx
  src/contexts/SpeakerContext.jsx
  src/contexts/SponsorsContext.jsx
  src/pages/SpeakerManagement.jsx
  src/pages/Sponsors.jsx
Labels: bug

#72 remove alert link in sidebar
  src/App.jsx
  src/components/Sidebar.jsx
  src/pages/Management.jsx
Labels: bug

#74 Scrum 236 guarantee that every plugin is able to create the necessary settings
  src/components/event_maker/pages/CommonInputs.jsx
  src/components/event_maker/pages/DynamicComponentConfiguration.jsx
  src/components/event_maker/pages/inputs/CheckboxInput.jsx
  src/components/event_maker/pages/inputs/MediaInput.jsx
  src/components/event_maker/pages/inputs/NumberInput.jsx
  src/components/event_maker/pages/inputs/SelectInput.jsx
  src/components/event_maker/pages/inputs/TextInput.jsx
  src/components/forms/Checkbox.jsx
  src/components/forms/ComposedText.jsx
  src/components/forms/Selector.jsx
  src/components/forms/ShortTextInput.jsx
  src/components/forms/TextInput.jsx
  src/components/plugins/PluginSettingsModal.jsx
  src/components/plugins/config/Checkbox.jsx
  src/components/plugins/config/FormControlWrapper.jsx
  src/components/plugins/config/NumberInput.jsx
  src/components/plugins/config/Radio.jsx
  src/components/plugins/config/Selector.jsx
  src/components/plugins/config/TextInput.jsx
  src/components/plugins/config/Toggle.jsx
  src/contexts/PluginsContext.jsx
  src/locales/en/translation.json
  src/locales/pt-BR/translation.json
  src/locales/pt-PT/translation.json
  src/pages/Instantiate.jsx
  src/pages/Plugins.jsx
Labels: enhancement

#75 Fix toggle and name handling
  src/components/plugins/config/Toggle.jsx
  src/contexts/PluginsContext.jsx
  src/pages/Plugins.jsx
Labels: bug

#77 Scrum 244 color on activity type
  src/components/activities/ActivityFilters.jsx
  src/components/activities/NewSessionTypeModal.jsx
Labels: enhancement

#76 fix names inn sidebar too
  src/components/common/Sidebar.jsx
  src/components/plugins/PluginSettingsModal.jsx
Labels: bug

#80 Feedback component done.
  src/components/event_maker/pages/components/FeedbackForm.jsx
  src/components/event_maker/pages/components/index.js
  src/locales/en/translation.json
  src/locales/pt-BR/translation.json
  src/locales/pt-PT/translation.json
Labels: enhancement

#83 Refresh after event creation
  src/components/common/CreateCard.jsx
  src/components/common/DropdownMenu.jsx
  src/components/common/Sidebar.jsx
  src/locales/en/translation.json
  src/locales/pt-BR/translation.json
  src/pages/Activities.jsx
  src/pages/EventSetup.jsx
  src/pages/Instantiate.jsx
  src/pages/Users.jsx
  src/styles.css
Labels: enhancement

#90 Scrum 270 calendar allows to insert activities outside event time range
  src/components/activities/ExcelImportModal.jsx
  src/components/activities/NewSessionModal.jsx
  src/pages/Activities.jsx
  src/pages/plugins/Schedule.jsx
Labels: bug, enhancement

#93 Component preview
  src/components/event_maker/pages/components/FloorPlan.jsx
  src/components/event_maker/pages/components/index.js
Labels: enhancement

#98 Logs removed
  src/components/activities/ExcelImportModal.jsx
  src/components/activities/NewSessionModal.jsx
  src/components/common/Sidebar.jsx
  src/components/event_maker/pages/DynamicComponentConfiguration.jsx
  src/components/event_maker/pages/inputs/MediaInput.jsx
  src/components/plugins/PluginSettingsModal.jsx
  src/components/users/UserExcelImport.jsx
  src/contexts/AlertsContext.jsx
  src/contexts/ComponentsContext.jsx
  src/contexts/EventContext.jsx
  src/contexts/MediaContext.jsx
  src/contexts/MenuContext.jsx
  src/contexts/PagesContext.jsx
  src/contexts/PluginsContext.jsx
  src/contexts/ThemeContext.jsx
  src/contexts/UsersContext.jsx
  src/hooks/useSections.js
  src/keycloak.js
  src/lib/i18n.js
  src/pages/Activities.jsx
  src/pages/AuthRedirect.jsx
  src/pages/EventSetup.jsx
  src/pages/Home.jsx
  src/pages/Instantiate.jsx
  src/pages/PagesList.jsx
  src/pages/Plugins.jsx
  src/pages/Users.jsx
  src/pages/page_editor/CreatePage.jsx
  src/pages/page_editor/EditPage.jsx
  src/pages/plugins/Sponsors.jsx
  src/services/KeycloakAdminService.js
  src/utils/keycloakAdminUtils.js
Labels: bug

#97 User does not get stuck on empty page
  src/pages/PagesList.jsx
Labels: bug

#100 Add feedback page
  src/App.jsx
  src/locales/en/translation.json
  src/locales/pt-BR/translation.json
  src/locales/pt-PT/translation.json
  src/pages/plugins/ActivitiesFeedback.jsx
Labels: enhancement

#102 Pwa on frontend
  public/pwa-192x192.png
  public/pwa-512x512.png
  src/App.jsx
  src/components/common/Sidebar.jsx
  src/contexts/EventContext.jsx
  src/contexts/ManifestContext.jsx
  src/contexts/Provider.jsx
  src/locales/en/translation.json
  src/locales/pt-BR/translation.json
  src/locales/pt-PT/translation.json
  src/pages/EventEditor.jsx
  src/pages/IconsEditor.jsx
Labels: enhancement

#92 Improvments on Floor Plan Management Page
  src/components/floorplans/FloorPlanModal.jsx
  src/components/floorplans/SortableItem.jsx
  src/locales/en/translation.json
  src/locales/pt-BR/translation.json
  src/locales/pt-PT/translation.json
  src/pages/plugins/FloorPlans.jsx
Labels: enhancement

#103 Various fixes to menu and pages
  src/components/event_maker/pages/inputs/PageDescriptionInput.jsx
  src/contexts/PagesContext.jsx
  src/locales/en/translation.json
  src/locales/pt-BR/translation.json
  src/locales/pt-PT/translation.json
  src/pages/PagesList.jsx
  src/pages/page_editor/CreatePage.jsx
  src/pages/page_editor/EditPage.jsx
Labels: bug, enhancement

#104 improve color page looks
  src/components/event_maker/ThemeCustomizer.jsx
Labels: enhancement

#105 change url from navigate
  src/pages/page_editor/EditPage.jsx
Labels: bug

#133 Hotfix/timezones conversion
  src/App.jsx
  src/components/activities/CreateActivityModal.jsx
  src/components/activities/EditActivityModal.jsx
  src/components/event_maker/ColorSelector.jsx
  src/components/event_maker/ThemeCustomizer.jsx
  src/components/event_maker/pages/DynamicComponentConfiguration.jsx
  src/components/event_maker/pages/components/Button.jsx
  src/components/event_maker/pages/components/Text.jsx
  src/components/event_maker/pages/components/Title.jsx
  src/components/event_maker/pages/components/utils.js
  src/pages/Colors.jsx
  src/pages/plugins/Schedule.jsx
  src/pages/plugins/SpeakerManagement.jsx
  src/utils/date.js
Labels: bug

#132 date utils
  src/components/activities/CreateActivityModal.jsx
  src/components/activities/EditActivityModal.jsx
  src/pages/plugins/Schedule.jsx
  src/utils/date.js
Labels: bug

#135 Hotfix/add type color activity card
  src/components/activities/ActivityList.jsx
  src/components/common/Activity.jsx
  src/locales/en/translation.json
  src/locales/pt-BR/translation.json
  src/locales/pt-PT/translation.json
  src/pages/Activities.jsx
Labels: enhancement

#134 fixes
  src/components/activities/ActivityList.jsx
  src/components/common/Activity.jsx
  src/locales/en/translation.json
  src/locales/pt-BR/translation.json
  src/locales/pt-PT/translation.json
  src/pages/Activities.jsx
Labels: enhancement

#137 fix event times when dragging
  src/pages/plugins/Schedule.jsx
Labels: bug

#139 Fix/event hours timezone
  src/pages/EventEditor.jsx
  src/pages/Plugins.jsx
Labels: bug

#142 fix complete
  src/pages/plugins/SpeakerManagement.jsx
Labels: bug
